language: php

matrix:
  include:
    - php: 7.4
      env:
        - CS_CHECK=true
    - php: 7.4

before_install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit
  - if [[ $CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi

notifications:
  email: false
